all: lab1 lab2

lab1: ./src/lab1.cpp
	mpicxx -Wall -o ./bin/lab1 ./src/lab1.cpp

lab2: ./src/lab2.cpp
	mpicxx -Wall -o ./bin/lab2 ./src/lab2.cpp

clean:
	rm -rf ./bin/lab1 ./bin/lab2 ./bin/lab3 ./bin/lab4